#%%
# This script is used to clean up a LaTeX file generated by LyX.
# It removes the extra newlines.
# 2024 01 Andrew Chen

#%%
# setup
import os
import re

#%%
# read file
with open('post_hoc.tex', 'r') as file:
    content = file.read()

#%%
# replace the pattern [stuff]\n[stuff] with [stuff][space][stuff]
# where stuff is standard stuff
content = re.sub(r'(?<=[a-zA-Z0-9.,``\'\'?!])\n(?=[a-zA-Z0-9.,``\'\'?!])', ' ', content)


#%%
# check preamble
temp = 100
print(content[temp:temp+200])
repr(content[temp:temp+200])

#%%
# check text
temp = 1000
print(content[temp:temp+200])
repr(content[temp:temp+200])


#%%
# write file
with open('post_hoc.tex', 'w') as file:
    file.write(content)


# %%
